"""Keep the committed standalone-engine rules identical to variants.ini."""
from pathlib import Path
import sys
root = Path(__file__).resolve().parents[1]
src = root / 'native/Fairy-Stockfish/src'
ini = (src / 'variants.ini').read_text()
block = ini.split('# BEGIN JANGGI LAB VARIANTS\n', 1)[1].split('# END JANGGI LAB VARIANTS', 1)[0]
output = '// Generated by scripts/embed_variants.py; edit variants.ini.\nR"JANGGI(\n' + block + ')JANGGI"\n'
header = src / 'janggi_variants.inc'
if '--check' in sys.argv:
    assert header.read_text() == output, 'Run python scripts/embed_variants.py'
else:
    header.write_text(output)
